allowBuilds:
  '@parcel/watcher': true
  core-js: true
  cpu-features: true
  esbuild: true
  sharp: true
  ssh2: true
  unrs-resolver: true
overrides:
  jspdf@<3.0.1: '>=3.0.1'
  dompurify@<3.2.4: '>=3.2.4'
  jspdf@<=3.0.1: '>=3.0.2'
