CREATE TABLE pd_log (
	id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	timestamp BIGINT(20) UNSIGNED NOT NULL,
	actorId INT UNSIGNED NOT NULL,
	subjectId INT UNSIGNED NOT NULL,
	field VARCHAR(64) NOT NULL,
	operation VARCHAR(64) NOT NULL,
	INDEX idx_subjectId (subjectId)
);
